name = "Ket"
uuid = "412c778c-4733-41d8-b706-9e072557ba34"
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[weakdeps]
CyclotomicNumbers = "c380f8b6-65b3-4789-a31b-7d6b5dc6d4c5"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extensions]
KetExact = "CyclotomicNumbers"
KetSparse = "SparseArrays"

[compat]
DoubleFloats = "1.3.8"
GenericLinearAlgebra = "0.3"
Nemo = "0.39 - 0.45"
Quadmath = "0.5.10"
julia = "1.9"

[extras]
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
Quaternions = "94ee1d12-ae83-5a48-8b1c-48b8ff168ae0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CyclotomicNumbers", "DoubleFloats", "Quadmath", "Quaternions", "Test"]
