name = "Ket"
uuid = "412c778c-4733-41d8-b706-9e072557ba34"
version = "0.2.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Dualization = "191a621a-6537-11e9-281d-650236a99e60"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
Hypatia = "b99e6be6-89ff-11e8-14f8-45c827f4f8f2"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
QuantumNPA = "5cd12e4b-1487-4eb2-a245-40f3146b84a8"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
CyclotomicNumbers = "c380f8b6-65b3-4789-a31b-7d6b5dc6d4c5"

[extensions]
KetExact = "CyclotomicNumbers"

[compat]
Combinatorics = "1"
CyclotomicNumbers = "0.1"
DoubleFloats = "1.4.0"
Dualization = "0.5.8"
GenericLinearAlgebra = "0.3.14"
Hypatia = "0.8.1"
JuMP = "1.23"
LinearAlgebra = "1"
Nemo = "0.47 - 0.48"
Quadmath = "0.5.10"
QuantumNPA = "0.1.0"
Random = "1"
SCS = "1 - 2"
SparseArrays = "1"
Test = "1"
julia = "1.10"

[extras]
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CyclotomicNumbers", "DoubleFloats", "Quadmath", "Random", "Test", "SCS"]
